### [De&C] Tugas 1
Sebuah lift memiliki daya tampung maksimum sebesar $C$ kg. $N$ orang mahasiswa saat ini berada di lantai 16. Masing-masing berat badan mahasiswa tersebut adalah $b_0, b_1, \dots b_{N-1}$. Karena terdapat agenda mendadak, manajemen gedung meminta perwakilan mahasiswa untuk dapat hadir di ruang rapat di lantai 1. Dengan batasan kapasitas lift, berapa jumlah mahasiswa terbanyak (dan siapa sajakah yang akan ditunjuk) yang sebaiknya diutus untuk mengikuti pertemuan tersebut dengan mobilisasi menggunakan lift?

Selesaikan masalah di atas dengan algoritma berkompleksitas waktu $\mathcal{O}(2^{N})$ dan kompleksitas ruang $\mathcal{O}(N)$. Rancanglah algoritma yang seefisien mungkin untuk kemungkinan *best case* yang mungkin terjadi.

In [6]:
def pecah_jadi_dua(arr):
    n = len(arr)

    # Bagi 2 : left & right
    mid = n // 2
    left = arr[0:mid]
    right = arr[mid:n]

    return left, right

def gabung(left,right):
    final_list = []     # Tempat menampung list yang telah digabung

    # Loop sampai list kiri dan list kanan habis
    while len(left) != 0 and len(right) != 0:
        # Lihat data yang lebih kecil untuk di append ke final_list
        if left[0] <= right[0]:
            data = left.pop(0)
            final_list.append(data)
        else:
            data = right.pop(0)
            final_list.append(data)

        # Kalau list kiri sudah habis dan list kanan masih ada, masukin sisanya
        if len(left) == 0 and len(right) != 0:
            for data in right:
                final_list.append(data)

        # Kalau list kanan sudah habis dan list kiri masih ada, masukin sisanya
        if len(right) == 0 and len(left) != 0:
            for data in left:
                final_list.append(data)

    return final_list

def urut(arr):
    # Langkah basis
    if len(arr) == 1:
        return arr

    # Pecah jadi 2 terus
    left,right = pecah_jadi_dua(arr)
    left = urut(left)
    right = urut(right)

    # Gabungin hasil pecahannya dalam bentuk yang terurut
    arr = gabung(left,right)

    return arr

# Misal:
def orang_yang_bisa_naik(C,data_mahasiswa,data_bb):
    # Tambal
    if len(data_mahasiswa) < 1:
        return "tidak ada orang"

    if len(data_mahasiswa) != len(data_bb):
        return "input tidak valid"

    nama_mahasiswa = []     # Tempat menampung nama mahasiswa yang bisa masuk lift
    count = 0         # Menghitung jumlah berat badan agar tidak lewat kapasitas lift
    jumlah_mahasiswa = 0    # Menghitung jumlah mahasiswa yang bisa masuk lift

    # Mengurutkan data berat badan dengan merge sort
    data_terurut = urut(data_bb)

    # Kalau data terkecilnya lebih besar dari kapasitas lift, return (Tambal)
    if data_terurut[0] > C:
        return "Lift tidak muat"

    # Mendata nama mahasiswa yang bisa masuk lift dan jumlah mahasiswa-nya
    for data in data_terurut:   # O(n)
        count += data
        if count <= C:
            data_index = data_bb.index(data)    # O(n)
            data_bb.pop(data_index)
            mahasiswa = data_mahasiswa.pop(data_index)
            nama_mahasiswa.append(mahasiswa)
            jumlah_mahasiswa +=1


    return f"ada {jumlah_mahasiswa} mahasiswa yang bisa naik lift, yaitu: \n {nama_mahasiswa}"

def main():
    # Misal:
    N = 10
    C = 300

    # Ada 10 orang mahasiswa dengan berat badan sebagai berikut:
    data_mahasiswa = ["Anto","Budi","Charlie","Dedi","Edi","Fina","Gading","Hari","Indah","Jojo"]
    data_bb = [70,62,75,89,73,55,68,88,50,82]

    print(orang_yang_bisa_naik(C,data_mahasiswa,data_bb))

if __name__ == '__main__':
    main()

[35, 50, 55, 62, 68, 70, 73, 75, 88, 89]
ada 5 mahasiswa yang bisa naik lift, yaitu: 
 ['Jojo', 'Indah', 'Fina', 'Budi', 'Gading']


### [De&C] Tugas 2

Rancanglah algoritma untuk penyelesaian Masalah Koin Palsu dengan setiap iterasinya membagi total koin ke dalam 3 bagian (timbangan yang digunakan tetap timbangan tradisional dengan 2 lengan), sedemikian sehingga efisiensi waktunya $\mathcal{O}(\log_3 N)$ dan efisiensi ruangnya $\mathcal{O}(1)$.

In [6]:
N = int(input("Inputkan banyak koin yang akan ditimbang: "))
fake = int(input("Koin ke berapa yang palsu? (koin 0 s.d. koin n-1): "))


def scale(L1,R1,L2,R2):
    global fake

    # return -1 jika koin palsu di antara L1 sampai R1-1
    if L1 <= fake and fake < R1:
        return -1

    # return 1 jika koin palsu di antara L2 sampai R2
    if L2 <= fake and fake < R2:
        return 1

    # return 0 jika seimbang
    return 0

def FindFake(left, right, num_of_scaling):
    global N,fake

    if fake > N-1 or N<1 or fake < 0:
        return "Input Anda tidak valid"
    numCoins = right - left

    # kalau koinnya tinggal 1, ketemu
    if numCoins == 1:
        print("Ketemu! Koin palsu adalah koin ", left)
        print("\tTotal penimbangan dilakukan:", num_of_scaling)
        return

    print("Sekarang kita meninjau koin", left, "hingga koin", right - 1)

    # Batas
    border = int(numCoins / 3)
    if border == 0:
        border = 1

    # Mendefinisikan left dan right pertama dan kedua
    first_right = left + border - 1

    second_left = left + border
    second_right = first_right + border

    # Penimbangan
    scaling_result = scale(left, first_right + 1, second_left, second_right + 1)
    num_of_scaling += 1

    print("Letakkan koin", left, "hingga koin", first_right, "di sebelah kiri tangan timbangan.")
    print("Letakkan koin", second_left, "hingga koin", second_right, "di sebelah kanan tangan timbangan.")

    # Cek hasil timbangan
    # Lakukan rekursif sampai dapat koinnya
    if scaling_result == -1:
        print("\tHasil Penimbangan", num_of_scaling, ": Tangan sebelah kiri lebih ringan\n")
        FindFake(left, first_right + 1, num_of_scaling)
    elif scaling_result == 1:
        print("\tHasil Penimbangan", num_of_scaling, ": Tangan sebelah kanan lebih ringan\n")
        FindFake(second_left, second_right + 1, num_of_scaling)
    else:
        print("\tHasil Penimbangan", num_of_scaling, ": Kedua tangan seimbang. Next! \n")
        FindFake(second_right + 1, right, num_of_scaling)

FindFake(0, N, 0)

Sekarang kita meninjau koin 0 hingga koin 9
Letakkan koin 0 hingga koin 2 di sebelah kiri tangan timbangan.
Letakkan koin 3 hingga koin 5 di sebelah kanan tangan timbangan.
	Hasil Penimbangan 1 : Kedua tangan seimbang. Next! 

Sekarang kita meninjau koin 6 hingga koin 9
Letakkan koin 6 hingga koin 6 di sebelah kiri tangan timbangan.
Letakkan koin 7 hingga koin 7 di sebelah kanan tangan timbangan.
	Hasil Penimbangan 2 : Kedua tangan seimbang. Next! 

Sekarang kita meninjau koin 8 hingga koin 9
Letakkan koin 8 hingga koin 8 di sebelah kiri tangan timbangan.
Letakkan koin 9 hingga koin 9 di sebelah kanan tangan timbangan.
	Hasil Penimbangan 3 : Tangan sebelah kanan lebih ringan

Ketemu! Koin palsu adalah koin  9
	Total penimbangan dilakukan: 3


### [Di&C] Tugas 3

Implementasikan Algoritma Quick Sort dengan efisiensi waktu rata-rata $\mathcal{O}(n \log n)$ dan efisiensi ruang $\mathcal{O}(n \log n)$.

In [2]:
### Quick Sort ###
def partition(arr, start, finish):
    pivot = arr[start] # Menjadikan arr[start] menjadi pivot pada partisi berikut
    i = start + 1
    j = finish
    done = False # Berguna untuk memberhentikan loop partisi
    while not done: # Kompleksitas waktu O(n)
        # Validasi
        while i <= j and arr[i] <= pivot: #Jika nilai i lebih kecil sama dengan j dan value dari array[i] lebih kecil sama dengan pivot:
            i += 1 # i digeser ke kanan
        while j >= i and arr[j] >= pivot: #Jika nilai j lebih besar sama dengan i dan value dari array[j] lebih besar sama dengan pivot:
            j -= 1 # j digeser ke kiri
        # Jika i dan j sudah bersilang dalam pengecekan array, maka loop dihentikan
        if i > j: # Jika i dan j sudah saling bersilang posisi maka :
            done = True # loopnya terhenti
        else :
            # Tukar posisi value i dan j jika right > left
            arr[i], arr[j] = arr[j], arr[i]
    # Tuker posisi pivot
    arr[start], arr[j] = arr[j], arr[start]
    return j # Kembalikan indeks posisi dari j untuk dijadikan pivot_index

def quick_sort(arr, start, finish):
    if start < finish:
        pivot_index = partition(arr, start, finish)
        quick_sort(arr, start, (pivot_index - 1)) # Mensortir bagian kiri
        quick_sort(arr, (pivot_index + 1), finish) # Mensortir bagian kanan

# Main
arr = [3, 6, 6, 10, 2, 4, 5, 8] # Kompleksitas ruang  = O(n)
length = len(arr)
quick_sort(arr, 0, (length - 1))
print(arr)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,

### [Di&C] Tugas 4

Implementasikan Algoritma Strassen Matrix Multiplication dengan efisiensi waktu $\mathcal{O}(n^{\log_2 7})$ dan efisiensi ruang $\mathcal{O}(n^2 \log n)$

In [1]:
import numpy as np

# Cek apakah dia bilangan 2^x
def is_power_of_2(n):
    while n>1:
        if n % 2 != 0:
            return False
        n = n // 2
    return True

def split(A, B):
    # Cari dimensi matrix A dan B
    row_A, col_A = A.shape
    row_B, col_B = B.shape

    # Kalau misalnya matriksnya berdimensi 2^n x 2^n, tidak perlu padding
    if row_A == col_A == row_B == col_B and is_power_of_2(row_A):
        mid = row_A // 2
        A00 = A[:mid, :mid]
        A01 = A[:mid, mid:]
        A10 = A[mid:, :mid]
        A11 = A[mid:, mid:]
        B00 = B[:mid, :mid]
        B01 = B[:mid, mid:]
        B10 = B[mid:, :mid]
        B11 = B[mid:, mid:]
        return A00, A01, A10, A11, B00, B01, B10, B11

    # Buat matrix baru berukuran 2^n x 2^n terdekat
    new_size = 1
    while new_size < max(row_A, row_B, col_A, col_B):
        new_size *= 2

    # Padding matriks A dan B supaya dimensinya new_size x new_size
    pad_A = np.zeros((new_size, new_size))
    pad_B = np.zeros((new_size, new_size))

    # Masukin isi matrix A dan B ke dalam matriks baru yaitu pad_A dan pad_B
    pad_A[:row_A, :col_A] = A
    pad_B[:row_B, :col_B] = B

    # Pembagian matrix blok
    mid = new_size // 2
    A00 = pad_A[:mid, :mid]
    A01 = pad_A[:mid, mid:]
    A10 = pad_A[mid:, :mid]
    A11 = pad_A[mid:, mid:]
    B00 = pad_B[:mid, :mid]
    B01 = pad_B[:mid, mid:]
    B10 = pad_B[mid:, :mid]
    B11 = pad_B[mid:, mid:]
    return A00, A01, A10, A11, B00, B01, B10, B11


def strassen_matrix_multiply(A, B):
    # Cari dimensi matrix A dan B
    row_A,col_A = A.shape
    row_B,col_B = B.shape

    # Basis, jika matrix berukuran 1x1 maka menjadi best case.!
    if row_A == col_A == row_B == col_B == 1:
        return A * B

    A00, A01, A10, A11, B00, B01, B10, B11 = split(A,B)

    # Langkah rekursif untuk menghitung 7 (P)
    m1 = strassen_matrix_multiply(A00 + A11, B00 + B11)
    m2 = strassen_matrix_multiply(A10 + A11, B00)
    m3 = strassen_matrix_multiply(A00, B01 - B11)
    m4 = strassen_matrix_multiply(A11, B10 - B00)
    m5 = strassen_matrix_multiply(A00 + A01, B11)
    m6 = strassen_matrix_multiply(A10 - A00, B00 + B01)
    m7 = strassen_matrix_multiply(A01 - A11, B10 + B11)

    # Menggabungkan hasil perhitungan strassen ke dalam bentuk C
    C00 = m1 + m4 - m5 + m7
    C01 = m3 + m5
    C10 = m2 + m4
    C11 = m1 + m3 - m2 + m6

    # Mengabungkan submatrix C menjadi 1 (result)
    result = np.vstack((np.hstack((C00, C01)), np.hstack((C10, C11))))

    # Dimensi matriks hasil yang diharapkan
    desired_shape = (row_A, col_B)

    # Jika sudah sesuai dimensinya dengan row_A x col_B maka tinggal di return resultnya
    if result.shape == desired_shape:
        return result
    else:
        # Kalau masih belum kita harus ngedelete kolom serta baris yang menjadi padding dalam kode tersebut
        while result.shape[0] > row_A:
            result = np.delete(result, -1, axis=0)
        while result.shape[1] > col_B:
            result = np.delete(result, -1, axis=1)
        return result


# Main
A = np.array([[1, 2, 3, 4, 5, 6],
              [7, 8, 9, 10, 11, 12],
              [13, 14, 15, 16, 17, 18],
              [19, 20, 21, 22, 23, 24],
              [25, 26, 27, 28, 29, 30]])

B = np.array([[31, 32, 33, 34, 35, 36],
              [37, 38, 39, 40, 41, 42],
              [43, 44, 45, 46, 47, 48],
              [49, 50, 51, 52, 53, 54],
              [55, 56, 57, 58, 59, 60],
              [61, 62, 63, 64, 65, 66]])

result = strassen_matrix_multiply(A, B)
print(result)

[[1071. 1092. 1113. 1134. 1155. 1176.]
 [2727. 2784. 2841. 2898. 2955. 3012.]
 [4383. 4476. 4569. 4662. 4755. 4848.]
 [6039. 6168. 6297. 6426. 6555. 6684.]
 [7695. 7860. 8025. 8190. 8355. 8520.]]
